### ISSUE TITLE
Browser compatible bower build

### ISSUE THREAD

**Issue by blainekasten** [Financial-Times/ftdomdelegate#65]
Given that bower is used for front-end package management. What are your thoughts on making a browserified build and have the bower.json set the main to that file?

I'm currently trying to use this with bower_rails which when using ftdomdelegate, errors out due to the `module`. 

My only options currently is to download the build code, or try and mangle browserify into the ftdomdelegate in the bower rails loading.

If this is something you're interested in, I'll totally do the labor to make it happen.

**Comment by notlee** [comment]
Thanks for opening this blainekasten. Closing this as we don't have plans to publish bundled versions of [Origami](https://origami.ft.com/)-maintained components currently, and it's [no longer needed](https://github.com/Financial-Times/ftdomdelegate/pull/66#issuecomment-529490854).
