### ISSUE TITLE
Why are there two names for this module?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/ftdomdelegate#88]
I've got both ftdomdelegate and dom-delegate installed in my bower_components when using Origami modules.

Why are there two different names? Which is the correct one to use?

**Comment by matthew-andrews** [comment]
reasons.

😭 😭 😭 

it was called dom-delegate originally but there was a sort of name standardisation drive at some point where it was renamed to ftdomdelegate.  now it's a mess.

**Comment by callumlocke** [comment]
Fair enough :) Which one should I use if I were to create a new Origami module?

**Comment by orangemug** [comment]
Both bower and npm use `dom-delegate` so it would make sense to use that in my opinion. Also renaming the repo to match would be nice too, I've always found that odd.

**Comment by onishiweb** [comment]
Inside the FT it should be `ftdomdelegate` See: https://github.com/ftlabs/ftdomdelegate/issues/77#issuecomment-168982928

**Comment by notlee** [comment]
vs renamed to ftdomdelegate
