### ISSUE TITLE
IE10 click event doesn't work on an SVG.

### ISSUE THREAD

**Issue by matine** [Financial-Times/ftdomdelegate#89]
Currently throwing an exception trying to call getAttribute function

**Comment by bakura10** [comment]
I have this issue as well, although I do not directly attach the listener to an SVG but to a click that ocntains the SVG. When the padding of the link is clicked, it works properly, however when the inner SVG is clicked exactly, listener is not called.

Is there a way to solve this issue? It works properly on IE11+ :).

**Comment by magicspon** [comment]
Any joy? Just come across this issue

**Comment by notlee** [comment]
Hi all, this should be fixed by [backflip's pr](https://github.com/Financial-Times/ftdomdelegate/pull/97) and will go out in the next release (v3.1.0).
